version: 2

templates:
  gomod-template: &gomod-template
    working_directory: /home/circleci/uio
    environment:
      - CGO_ENABLED: 0
      - GO111MODULE: "on"

  go116-template: &go116-template
    docker:
      - image: circleci/golang:1.16

workflows:
  version: 2
  build:
    jobs:
      - clean
      - build:
          requires:
            - clean

jobs:
  clean:
    <<: [*go116-template, *gomod-template]
    steps:
      - checkout
      - run:
          name: vet
          command: go vet ./...
      - run:
          name: gofmt
          command: |
            test -z "$(gofmt -s -l $(find -name '*.go' | grep -v /vendor/))"
      - run:
          name: go mod tidy
          command: |
            go mod tidy
            git status
            if [[ -n "$(git status --porcelain .)" ]]; then
              echo 'go.mod/go.sum is out-of-date: run `go mod tidy` and then check in the changes'
              echo 'If `go mod tidy` results in no changes, make sure you are using the latest relase of Go'
              git status --porcelain .
              exit 1
            fi

  build:
    <<: [*go116-template, *gomod-template]
    steps:
      - checkout
      - run: go env
      - run: go build ./...
      - run: go test ./...
      - run: ./cross-compile.sh
